import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as os from 'node:os';
import { logger } from '../utils/logger';

/**
 * Known Hermes env-var → provider-id mapping.
 * The env-var name is the canonical one used in `.env` and consumed by the
 * hermes Python process.
 */
export const HERMES_ENV_MAP: Record<string, { providerId: string; label: string }> = {
  OPENCODE_ZEN_API_KEY: { providerId: 'opencode', label: 'OpenCode Zen' },
  OPENROUTER_API_KEY: { providerId: 'openrouter', label: 'OpenRouter' },
  NVIDIA_API_KEY: { providerId: 'nvidia', label: 'NVIDIA NIM' },
  OPENAI_API_KEY: { providerId: 'openai', label: 'OpenAI' },
  ANTHROPIC_API_KEY: { providerId: 'anthropic', label: 'Anthropic' },
  NOUS_API_KEY: { providerId: 'nous', label: 'Nous Portal' },
  GOOGLE_API_KEY: { providerId: 'google', label: 'Google AI Studio' },
  DEEPSEEK_API_KEY: { providerId: 'deepseek', label: 'DeepSeek' },
};

/** Path to the Hermes .env file */
function hermesEnvPath(): string {
  return path.join(os.homedir(), 'AppData', 'Local', 'hermes', '.env');
}

class HermesEnvService {
  /**
   * Read the raw content of the Hermes .env file.
   * Returns null if the file doesn't exist or can't be read.
   */
  async readEnv(): Promise<string | null> {
    try {
      return await fs.readFile(hermesEnvPath(), 'utf-8');
    } catch {
      return null;
    }
  }

  /**
   * Write the full content back to the Hermes .env file.
   */
  async writeEnv(content: string): Promise<void> {
    await fs.writeFile(hermesEnvPath(), content, 'utf-8');
    logger.info(`Hermes .env updated (${(content.match(/\n/g) || []).length + 1} lines)`);
  }

  /**
   * Set an API key in the Hermes .env file.
   *
   * If the var already exists (commented or uncommented), it replaces the value.
   * If it doesn't exist, it appends the key at the end.
   *
   * Returns true if the file was modified.
   */
  async setKey(envVar: string, apiKey: string): Promise<boolean> {
    let content = await this.readEnv();
    if (content === null) {
      // File doesn't exist — create it
      content = `# Hermes Agent Environment Configuration\n# Auto-generated by Hermes VS Code extension\n\n`;
    }

    // Pattern: optionally commented line with the env var name
    // e.g. `# OPENCODE_ZEN_API_KEY=old` or `OPENCODE_ZEN_API_KEY=old`
    const escapedVar = envVar.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`^[ \\t]*#?[ \\t]*${escapedVar}=.*$`, 'gm');

    const newLine = `${envVar}=${apiKey}`;
    const match = regex.exec(content);

    if (match) {
      // Replace existing line (preserving position but uncommenting)
      content =
        content.slice(0, match.index) + newLine + content.slice(match.index + match[0].length);
    } else {
      // Append at the end (ensure trailing newline)
      if (!content.endsWith('\n')) content += '\n';
      content += `\n# ${envVar} — configured by Hermes VS Code extension\n${newLine}\n`;
    }

    await this.writeEnv(content);

    const info = HERMES_ENV_MAP[envVar];
    logger.info(`Hermes ${info?.label ?? envVar} API key ${match ? 'updated' : 'added'} in .env`);

    return true;
  }

  /**
   * Check if a specific env var is already set (uncommented) in the .env file.
   */
  async hasKey(envVar: string): Promise<boolean> {
    const content = await this.readEnv();
    if (!content) return false;
    // Look for uncommented `ENV_VAR=...` (non-empty value)
    const escapedVar = envVar.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`^[ \\t]*${escapedVar}=.+$`, 'm');
    return regex.test(content);
  }

  /**
   * Return the path to the Hermes .env file.
   */
  get path(): string {
    return hermesEnvPath();
  }
}

export const hermesEnvService = new HermesEnvService();
